algoritmo "ContarAtéAlgumNumero"
var
   valor,salto,contador:inteiro
inicio
      contador<-0
      Escreva("Quer contar até quanto? ")
      Leia(valor)
      Escreva("Qual será valor do salto? ")
      Leia(salto)
      Enquanto (contador<=valor) FACA
               Escreval(contador)
               contador<-contador+salto
      FimEnquanto
      Escreval("Terminei de contar")
fimalgoritmo
